---
title: "遺失值填補"
author: "高涵毅"
date: "2021/10/17"
output: html_document
---

```{r setup, include=FALSE}
library(reticulate)
knitr::knit_engines$set(python = reticulate::eng_python)
knitr::opts_chunk$set(echo = TRUE)
```

```{python}
import pandas as pd
import numpy as np
# import os
from IPython.display import display
from sklearn.model_selection import train_test_split
from tensorflow.random import set_seed
set_seed(69)

import missingno as msno
# %matplotlib inline

from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer, KNNImputer
from fancyimpute import SoftImpute, MatrixFactorization, BiScaler
# from fancyimpute import IterativeSVD, NuclearNormMinimization, SimilarityWeightedAveraging
from sklearn.pipeline import Pipeline

from sklearn.ensemble import RandomForestRegressor
from lightgbm import LGBMRegressor
from xgboost import XGBRegressor, XGBRFRegressor
from sklearn.metrics import mean_absolute_error

```

<!-- ```{python} -->
<!-- for i in range(1,8,1): -->
<!--     temp0_df = pd.read_csv(f"data{i}/train.csv", header=None, na_filter=False) -->
<!--     globals()[f'train{i}'] = temp0_df.iloc[:,:-1] -->
<!--     globals()[f'answer{i}'] = temp0_df.iloc[:,-1] -->
<!--     temp1_df = pd.read_csv(f"data{i}/test.csv", header=None) -->
<!--     globals()[f'test{i}'] = temp1_df.iloc[:,:-1] -->

<!-- ``` -->

```{r}
source_python("make_upload.py")

```

```{r}
for (j in 1:7) {
  PATH <- paste0(rep("data", 2), rep(j, 2), c("/train.csv", "/test.csv"))
  object <- paste0(c("train", "answer", "test"), rep(j, 3))
  temp0_df <- read.table(PATH[1], sep=",", na.strings=c("nan"))
  temp1_df <- read.table(PATH[2], sep=",", na.strings=c("nan"))
  assign(object[1], temp0_df[ , 1:ncol(temp0_df)-1])
  assign(object[2], temp0_df[ , ncol(temp0_df)])
  assign(object[3], temp1_df[ , 1:ncol(temp1_df)-1])
}

```

```{r}
# Grouping the left hand side
g = function(...) {
  List = as.list(substitute(list(...)))[-1L]
  class(List) = 'lbunch'
  return(List)
}

# Generic form
'%=%' = function(l, r, ...) UseMethod('%=%')

# Binary Operator
'%=%.lbunch' = function(l, r, ...) {
  Envir = as.environment(-1)

  if (length(r) > length(l))
    warning("RHS has more args than LHS. Only first", length(l), "used.")

  if (length(l) > length(r))  {
    warning("LHS has more args than RHS. RHS will be repeated.")
    r <- extendToMatch(r, l)
  }

  for (II in 1:length(l)) {
    do.call('<-', list(l[[II]], r[[II]]), envir=Envir)
  }
}

```

```{r, eval=FALSE}
library(missForest)
doParallel::registerDoParallel()
set.seed(seed=69, kind="L'Ecuyer-CMRG")
for (j in 1:7) {
  object <- paste0("temp_", "train", j)
  na_data <- get(paste0("train", j))
  col_names <- sapply(na_data, function(col) {length(unique(col)) <= 8} )
  if (sum(col_names) <= 1) 
    na_data[ , col_names] <- as.factor(na_data[ , col_names])
  else 
    na_data[ , col_names] <- lapply(na_data[ , col_names], factor)
  imputer <- missForest(xmis=na_data, maxiter=30, ntree=200, parallelize="forest")
  # X.imp <- imputer$ximp
  assign(object, imputer$ximp)
}

for (j in 1:7) {
  object <- paste0("temp_", "test", j)
  na_data <- get(paste0("test", j))
  col_names <- sapply(na_data, function(col) {length(unique(col)) <= 8} )
  if (sum(col_names) <= 1) 
    na_data[ , col_names] <- as.factor(na_data[ , col_names])
  else 
    na_data[ , col_names] <- lapply(na_data[ , col_names], factor)
  imputer <- missForest(xmis=na_data, maxiter=30, ntree=200, parallelize="forest")
  # X.imp <- imputer$ximp
  assign(object, imputer$ximp)
}

g(X_train, X_valid, y_train, y_valid) %=% train_test_split(r_to_py(train1), r_to_py(answer1), test_size=0.15, random_state=42L)

```

```{python, eval=FALSE}
states = ["train", "test"]
for state in states:
    for i in range(1,8,1):
        eval(f'r.temp_{state}{i}').round(2).to_csv(f'data{i}/{state}_forest_full.csv', header=None, index=None)

# for i in range(1,8,1):
#     concat = pd.concat([r[f'temp_train{i}'], pd.Series(r[f'answer{i}'])], axis=1)
#     concat.round(2).to_csv(f'data{i}/train_forest_full.csv', header=None, index=None)

```

```{python, eval=FALSE}
make_upload(imputer=None, status=True)

```

<!-- ## R Markdown -->

<!-- For more details on using R Markdown see <http://rmarkdown.rstudio.com>. -->

<!-- click the **Knit** button -->

<!-- ```{r cars} -->
<!-- summary(cars) -->
<!-- ``` -->

<!-- ## Including Plots -->

<!-- ```{r pressure, echo=FALSE} -->
<!-- plot(pressure) -->
<!-- ``` -->

<!-- Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot. -->
